blank_issues_enabled: true
contact_links:
  - name: Do you want to discuss PIP ideas or ask questions about the process?
    url: https://discord.gg/H5vZkNnXCu
    about: Use the Fellowship of Pactus in discord for PIP discussion!
